export const GET_SCREEN_SOURCES = 'GET_SCREEN_SOURCES';
export const SELECT_SCREEN_SOURCE = 'SELECT_SCREEN_SOURCE';
export const GET_MEDIA_STREAM = 'GET_MEDIA_STREAM';
export const RECORD_START = 'RECORD_START';
export const RECORD_STOP = 'RECORD_STOP';
